version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysqlsoria
    ports:
     - "${MYSQL_PORT}:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - network1       

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
     - "${PHPMYADMIN_PORT}:80"
    env_file: .env
    environment:
      PMA_HOST: ${PMA_HOST}
    networks:
      - network1

networks:
  network1:
    name: ${DOCKER_NETWORK}
#    external: true