DROP DATABASE IF EXISTS DB_SURVEYS;
CREATE DATABASE DB_SURVEYS
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DB_SURVEYS;

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;



CREATE TABLE CAREERS (
  ID_CAREER INT AUTO_INCREMENT PRIMARY KEY,
  NAME_CAREER VARCHAR(50) NOT NULL UNIQUE,
  STATUS_CAREER TINYINT DEFAULT 1
);

CREATE TABLE YEARS (
  ID_YEAR INT AUTO_INCREMENT PRIMARY KEY,
  VALUE_YEAR VARCHAR(50) NOT NULL UNIQUE,
  STATUS_YEAR TINYINT DEFAULT 1
);

INSERT INTO CAREERS (NAME_CAREER) VALUES ('SISTEMAS'),('LABORATORIO'),('CONTABLE'),('AMBIENTAL'),('ALL');

INSERT INTO YEARS (VALUE_YEAR) VALUES ('1'),('2'),('3'),('ALL');



-- Tabla de usuarios (admin o creadores de encuestas)
CREATE TABLE USERS (
  ID_USER INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ROLE ENUM('ADMIN', 'CREATOR') NOT NULL DEFAULT 'CREATOR',
  STATUS TINYINT DEFAULT 1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Insertar usuario administrador
INSERT INTO USERS (USERNAME, PASSWORD_HASH, ROLE) VALUES (
  'Administrador',
  'a4N5I491Srg308R6CDSD6O4cpbtRkd0kT325xEPdev0nU9H10Iu4y',
  'ADMIN'
);

-- Tabla de encuestas
CREATE TABLE POLLS (
  ID_POLL INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255),
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME NOT NULL,
  VISIBILITY VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
  STYLE TINYINT NOT NULL DEFAULT 1,
  STATUS TINYINT DEFAULT 1,
  ID_USER INT,
  MULTIPLE_CHOICE BOOLEAN DEFAULT FALSE,
  ID_CAREER INT NOT NULL,
  ID_YEAR INT NOT NULL,

  FOREIGN KEY (ID_CAREER) REFERENCES CAREERS( ID_CAREER ),

  FOREIGN KEY (ID_YEAR) REFERENCES YEARS ( ID_YEAR ),

  FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


-- Tabla de opciones
CREATE TABLE OPTIONS (
  ID_OPTION INT AUTO_INCREMENT PRIMARY KEY,
  ID_POLL INT,
  NAME_OPTION VARCHAR(100) NOT NULL,
  INFO_OPTION VARCHAR(255),
  AGE_OPTION TINYINT,
  CAREER_OPTION VARCHAR(20),
  PHOTO_OPTION VARCHAR(255),
  TYPE_ TINYINT NOT NULL,
  VOTES_OPTION INT DEFAULT 0,
  STATUS TINYINT DEFAULT 1,
  FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de votos
CREATE TABLE VOTES (
  ID_VOTE INT AUTO_INCREMENT PRIMARY KEY,
  ID_POLL INT NOT NULL,
  ID_OPTION INT,
  USER_IDENTIFIER VARCHAR(50) NOT NULL,
  STATUS TINYINT DEFAULT 1,
  FOREIGN KEY (ID_OPTION) REFERENCES OPTIONS(ID_OPTION)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;