DROP DATABASE IF EXISTS DB_SURVEYS;
CREATE DATABASE DB_SURVEYS
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE DB_SURVEYS;

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

-- Tabla de usuarios (admin o creadores de encuestas)
CREATE TABLE USERS (
  ID_USER INT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ROLE ENUM('ADMIN', 'CREATOR') NOT NULL DEFAULT 'CREATOR',
  STATUS TINYINT DEFAULT 1
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Insertar usuario administrador
INSERT INTO USERS (USERNAME, PASSWORD_HASH, ROLE) VALUES (
  'Administrador',
  '$2y$10$8H4RAhy.NVG9xrxzzfyoFe6f2oqAblY9OYtAJecJqb.gxLSy3Rjvi',
  'ADMIN'
);

-- Tabla de encuestas
CREATE TABLE POLLS (
  ID_POLL INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(255),
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME NOT NULL,
  VISIBILITY VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
  COLOUR TINYINT NOT NULL,
  STATUS TINYINT DEFAULT 1,
  ID_USER INT,
  MULTIPLE_CHOICE BOOLEAN DEFAULT FALSE,
  CAREERS VARCHAR(100) DEFAULT '["ALL"]',
  YEARS VARCHAR(50) DEFAULT '["3"]',
  FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de opciones de encuestas
CREATE TABLE OPTIONS (
  ID_OPTION INT AUTO_INCREMENT PRIMARY KEY,
  ID_POLL INT,
  TITLE_OPTION VARCHAR(100) NOT NULL,
  INFO_OPTION VARCHAR(255),
  VOTES_OPTION INT DEFAULT 0,
  STATUS TINYINT DEFAULT 1,
  PHOTO_OPTION VARCHAR(255),
  FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de candidatos
CREATE TABLE CANDIDATES (
  ID_CANDIDATE INT AUTO_INCREMENT PRIMARY KEY,
  ID_POLL INT,
  NAME_CANDIDATE VARCHAR(100) NOT NULL,
  INFO_CANDIDATE VARCHAR(255),
  AGE_CANDIDATE TINYINT,
  CAREER_CANDIDATE VARCHAR(20),
  PHOTO_CANDIDATE VARCHAR(255),
  VOTES_CANDIDATE INT DEFAULT 0,
  STATUS TINYINT DEFAULT 1,
  FOREIGN KEY (ID_POLL) REFERENCES POLLS(ID_POLL)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabla de votos
CREATE TABLE VOTES (
  ID_VOTE INT AUTO_INCREMENT PRIMARY KEY,
  ID_OPTION INT,
  ID_CANDIDATE INT,
  USER_IDENTIFIER VARCHAR(50) NOT NULL,
  STATUS TINYINT DEFAULT 1,
  FOREIGN KEY (ID_OPTION) REFERENCES OPTIONS(ID_OPTION),
  FOREIGN KEY (ID_CANDIDATE) REFERENCES CANDIDATES(ID_CANDIDATE)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;